# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verdi-doc.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(870, 1001)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.textEdit = QtGui.QTextEdit(Form)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout.addWidget(self.textEdit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Verdi GUI Commands", None))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">This is a list of commands for the Verdi GUI program and the Verdi laser.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Full documentation for Verdi GUI</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Found here: </span><a href=\"http://lisesavard.com/verdi-gui/\"><span style=\" font-size:9pt; text-decoration: underline; color:#0000ff;\">http://lisesavard.com/verdi-gui/</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">1.1 Verdi GUI commands</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">1.2 RS-232 commands for Verdi V-5</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">1.3 RS-232 queries for Verdi V-5</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">1.1 Verdi GUI commands</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<table border=\"1\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"0\" cellpadding=\"0\"><thead>\n"
"<tr>\n"
"<td bgcolor=\"#f0f0f0\" style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600; background-color:#f0f0f0;\">COMMAND</span><span style=\" font-size:9pt;\">        </span></p></td>\n"
"<td bgcolor=\"#f0f0f0\" style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600; background-color:#f0f0f0;\">ACTION PERFORMED</span></p></td></tr></thead>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">-help</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Print quick command reference</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">-baud</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Print current baudrate used for serial communication</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">-baud n</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Change baudrate to n.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">n = 1200, 2400, 4800, 9600, 19200, 38400, 57600</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Please note: the laser\'s baudrate must be set with the command &quot;BAUDRATE = n&quot;. Laser baudrate will update after this command is sent.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">-port</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Print name of USB port being used for serial communication</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">-port n</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Switch to a different port.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">n must be an integer value</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">-scan</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Perform a scan of all serial ports to see if a laser can be found.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">-update</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Fetch new laser stats.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">-update n</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Change frequency of automatic updates. Verdi GUI will automatically fetch new updates every n seconds.</span></p></td></tr></table>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">1.2 List of RS-232 Commands for the Verdi V-5</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt; font-weight:600;\"><br /></p>\n"
"<table border=\"1\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"0\" cellpadding=\"0\"><thead>\n"
"<tr>\n"
"<td bgcolor=\"#f0f0f0\" style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600; background-color:#f0f0f0;\">COMMAND</span><span style=\" font-size:9pt;\">        </span></p></td>\n"
"<td bgcolor=\"#f0f0f0\" style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600; background-color:#f0f0f0;\">ACTION PERFORMED</span></p></td></tr></thead>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">BAUDRATE = n </span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Sets the RS-232 Serial port baud rate to the specified value. n = 1200, 2400, 4800, 9600, 19200, 38400, 57600        </span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">CHILLER</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Enables Coherent-supplied chiller</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">ECHO = n</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">If n = 0, turns echo OFF. Characters send to the laser will not be echoed to the host. If n = 1, turns echo ON. Changes in echo mode will take effect with the first command sent after the ECHO command.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">EXIT = 1</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Duplicates the exit button on the laser power source.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">FLASH = 1</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Flashes laser output below lasing threshold to allow single-frequency mode (etalon) to recenter.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">KNOBDN = 1</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Duplicates KNOB DOWN button.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">LASER = n</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Key must be in the &quot;ON&quot; position in the power supply. If n = 0, puts the laser in STANDBY mode. If n = 1, resets faults and turns the laser on. Lasing will resume if no active faults.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">LBOH = n</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">If n = 0, turns LBO heater off (cooldown). If n = 1, turns LBO heater on (heating).</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">LBOOPT</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Initiates LBO optimization.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">LIGHT = nn.nnnn</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Sets light regulation to the specified output power.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">LFP = n</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">If n = 0, enables user input from power supply front panel. If n = 0, disables user input from power supply front panel.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">MENUDN = 1</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Duplicates MENU DOWN button from front panel.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">SELECT = 1</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Duplicates MENU SELECT button.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">MENUUP = 1</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Duplicates MENU UP button.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">POWER = nn.nnnn</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Sets light regulation to the specified output power. Same as LIGHT = nn.nnnn</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">PROMPT = n</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">If n = 0, turns &quot;Verdi&gt;&quot; prompt off. If n = 1, turns &quot;Verdi&gt;&quot; prompt on.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">SHUTTER = n</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">If n = 0, closes external shutter. If n = 1, opens external shutter.</span></p></td></tr></table>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">1.3 List of queries for the Verdi V-5</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt; font-weight:600;\"><br /></p>\n"
"<table border=\"1\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"0\" cellpadding=\"0\"><thead>\n"
"<tr>\n"
"<td bgcolor=\"#f0f0f0\" style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600; background-color:#f0f0f0;\">QUERY</span><span style=\" font-size:9pt;\">        </span></p></td>\n"
"<td bgcolor=\"#f0f0f0\" style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600; background-color:#f0f0f0;\">RETURNED INFORMATION</span></p></td></tr></thead>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?ACAD </span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns the average diode current and the difference between them.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?BT</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns laser head baseplate temperature, nn.nn, in degrees C.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?B</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns the baudrate of the Verdi V-5 serial port.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?C</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns measured average diode current, nn.n, in amps.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?D1C</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns laser diode 1 measured current, nn.n, in amps.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?D1HST</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns diode 1 heatsink temperature, nn.nn, in degrees C.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?D1H</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns number of operating hours on laser diode 1.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?D1PC</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns light output from diode 1 photocell.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?D1RCF</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns the factor that accounts for diode aging for diode 1.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?D1RCM</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns maximum current at which diode 1 will be allowed to operate.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?D1SS</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns status of diode 1 temperature servo:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">0 if the servo is OPEN</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">1 if the servo is LOCKED</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">2 if the servo is SEEKING</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">3 if the servo has a FAULT</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">4 if the servo is OPTIMIZING</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">5 if the servo is CPEAKING</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">6 if the servo is CPEAKING2</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?D1ST</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns laser diode 1 set temperature, nn.nn, in degrees C.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?D1TD</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns diode 1 temperature servo drive setting.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?D1T</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns diode 1 measure temperature, nn.nn, in degrees C.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?D15V</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns reference voltage used to measure the temperature of diode 1.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?DIOS</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Prints diode optimizer status.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">1 if system is able to optimize.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">0 if system is not able to optimize.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?ED</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns etalon temperature servo drive setting.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?ESS</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns the status of the etalon temperature servo.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">0 if the servo is OPEN.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">1 if the servo is LOCKED.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">2 if the servo is SEEKING.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">3 if the servo has a FAULT.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?EST</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns etalon set temperature, nn.nn, in degress C.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?ET</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns etalon measured temperature, nn.nn, in degrees C.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?F</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Prints faults. See Laser Operator\'s Manual for list of fault codes.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?FH</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns list of numbered codes for all faults that have occurred since the last LASER ON command, separated by an &quot;&amp;&quot;, or return SYSTEM OK if no latched faults. To clear the fault screen, when the fault is active, enter the LASER ON or EXIT command.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?HH</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns the number of operating hours on the system head.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?K</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">0 if the keyswitch is OFF</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">1 if the keyswitch is ON</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?L</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">0 if the LASER is OFF (STANDBY)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">1 if the LASER is ON</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">2 if the LASER is OFF due to fault</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?LBOD</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns LBO temperature servo drive setting.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?LBOOS</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns the LBO optimizer status:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">1 if the system is able to run LBO optimization</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">0 if not</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?LBOST</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns the LBO set temperature, nnn.nn, in degrees C.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?LBOSS</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns the status of the LBO temperature servo:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">0 if the servo is OPEN</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">1 if the servo is LOCKED</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">2 if the servo is SEEKING</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">3 if the servo has a FAULT</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">4 if the servo is OPTIMIZING</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">5 if the servo is CPEAKING</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">6 if the servo is CPEAKING2</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?LBOT</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns the LBO measured temperature, nnn.nn, in degrees C.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?L</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns the calibrated output power, nn.nnn, in watts.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?LRS</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns the status of the light loop servo:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">0 if the servo is OPEN</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">1 if the servo is LOCKED</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">2 if the servo is SEEKING</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">3 if the servo has a FAULT</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?M</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns the mode of operation, whether current or light control.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">1 = light, 0 = current</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?PSH</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns the number of power supply operating hours.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?SP</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns the light regulation set power, nn.nnnn, in watts.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?S</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns the status of the external shutter.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">0 if the shutter is CLOSED</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">1 if the shutter is OPEN</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?SV</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns the power supply software version number.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?VST</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns the vanadate #1 set temperature, nn.nn, in degrees C.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?VT</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns the vanadate #1 measured temperature, nn.nn, in degrees C.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?VD</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns the vanadate #1 temperature servo drive setting.</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">?VSS</span></p></td>\n"
"<td style=\" padding-left:8; padding-right:8; padding-top:8; padding-bottom:8;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Returns the status of the vanadate #1 temperature servo:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">0 if the servo is OPEN</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">1 if the servo is LOCKED</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">2 if the servo is SEEKING</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">3 if the servo has a FAULT</span></p></td></tr></table></body></html>", None))

